// Generated by IcedCoffeeScript 1.7.1-c
(function() {
  var E, ie;

  ie = require('iced-error');

  module.exports = E = ie.make_errors({
    UNKNOWN_METHOD: "No method available",
    EOF: "EOF from server"
  });

  E.UnknownMethodError.prototype.toString = function() {
    return "unknown method: " + this.method;
  };

}).call(this);
