// Generated by IcedCoffeeScript 108.0.8
(function() {
  var net_module;

  net_module = null;

  exports.set_net_module = function(m) {
    return net_module = m;
  };

  exports.get_net_module = function() {
    return net_module;
  };

}).call(this);
