// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var mp2, pp, _opts;

  try {
    mp2 = require('msgpack2');
  } catch (e) {

  }

  try {
    pp = require('purepack');
  } catch (e) {

  }

  if ((mp2 == null) && (pp == null)) {
    throw new Error("Need either msgpack2 or purepack to run");
  }

  _opts = null;

  exports.set_opts = function(o) {
    var _pack_opts;
    return _pack_opts = o;
  };

  exports.pack = function(b) {
    var ret;
    ret = mp2 ? mp2.pack(b) : pp ? pp.pack(b, 'buffer', _opts) : void 0;
    return ret;
  };

  exports.unpack = function(b) {
    var dat, pw, _ref;
    if (mp2) {
      dat = mp2.unpack(b);
      pw = null;
    } else if (pp) {
      _ref = pp.unpack(b), pw = _ref[0], dat = _ref[1];
    }
    if (pw) pw = pw.join("; ");
    return [pw, dat];
  };

}).call(this);
