// Generated by IcedCoffeeScript 1.6.2a
(function() {
  var e, mp, pp, _opts;



  try {
    mp = require('msgpack');
  } catch (_error) {
    e = _error;
  }

  if (mp == null) {
    try {
      mp = require('msgpack4');
    } catch (_error) {
      e = _error;
    }
  }

  if (mp == null) {
    try {
      pp = require('purepack');
    } catch (_error) {
      e = _error;
    }
  }

  if ((mp == null) && (pp == null)) {
    throw new Error("Need either msgpack, msgpack4 or purepack to run");
  }

  _opts = {};

  exports.set_opts = function(o) {
    var _pack_opts;
    return _pack_opts = o;
  };

  exports.pack = function(b) {
    var ret;
    ret = mp ? mp.pack(b) : pp ? pp.pack(b, 'buffer', _opts) : void 0;
    return ret;
  };

  exports.unpack = function(b) {
    var dat, pw, _ref;
    pw = null;
    if (mp) {
      dat = mp.unpack(b);
    } else if (pp) {
      _ref = pp.unpack(b), pw = _ref[0], dat = _ref[1];
    }
    if (pw) {
      pw = pw.join("; ");
    }
    return [pw, dat];
  };

}).call(this);
